config_vars: /app/configs/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        user-repo:
        friend-repo:
        user-service:
        friend-service:
        jwt-verifier:
            public-key-path: /run/secrets/public.pem
        cookie-factory:
            secure-refresh-tk: $secure-auth-cookie

        testsuite-support: {}

        congestion-control:
            only-rtc: false
            fake-mode: $is-testing

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-signup:
            path: /api/v2/auth/signup
            method: POST
            task_processor: main-task-processor
            max_request_size: 2048 # 2KB

        handler-login:
            path: /api/v2/auth/login
            method: POST
            task_processor: main-task-processor
            max_request_size: 2048 # 2KB

        handler-refresh:
            path: /api/v2/auth/refresh
            method: POST
            task_processor: main-task-processor
            max_request_size: 2048 # 2KB

        postgres-db-1:
            dbconnection: $pg-connection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        grpc-server:
            port: $grpc-server-port
            port#fallback: 8091
            completion-queue-count: 3
 
        grpc-friend-server:
            task-processor: main-task-processor