services:
  devcontainer:
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    volumes:
      - .:/app:rw
      - ./shared/keys/dev:/run/secrets:ro
      - ./.vcpkg/cache:/opt/vcpkg_cache/:rw
      - ./.vcpkg/installed:/opt/vcpkg_installed:rw
    environment:
      POSTGRES_CONNECTION: ${POSTGRES_CONNECTION}
      VCPKG_ROOT: /opt/vcpkg
      VCPKG_MANIFEST_DIR: /app/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: /opt/vcpkg_cache
      VCPKG_INSTALLED_DIR: /opt/vcpkg_installed
    command: sleep infinity
    networks:
      - dev

    # cap-add & seccomp are for debugger to work properly
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

networks:
  dev:
    driver: bridge