FROM ghcr.io/userver-framework/ubuntu-22.04-userver-pg-dev:v2.15

RUN apt-get install -y clang-18 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/clang-18 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 100 \
    && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

ENV CC=/usr/bin/clang-18 \
    CXX=/usr/bin/clang++-18

# Install argon2 for password hashing
RUN apt-get install -y libargon2-dev

# Install jwt-cpp
RUN git clone https://github.com/Thalhammer/jwt-cpp.git /tmp/jwt-cpp \
    && cp -r /tmp/jwt-cpp/include/* /usr/include/ \
    && rm -rf /tmp/jwt-cpp

# Install minio
RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio \
    -O /usr/local/bin/minio && chmod +x /usr/local/bin/minio

ARG VCPKG_ROOT=/opt/vcpkg
RUN apt-get install -y zip ninja-build \
    && git clone --depth 1 https://github.com/microsoft/vcpkg.git $VCPKG_ROOT \
    && $VCPKG_ROOT/bootstrap-vcpkg.sh \
    && chmod 777 -R $VCPKG_ROOT \
    && chmod g+s $VCPKG_ROOT