FROM ghcr.io/userver-framework/ubuntu-22.04-userver-pg-dev:v2.15

ARG UID=1000
ARG GID=1000

# Install argon2 for password hashing
RUN apt-get install -y libargon2-dev

# Install jwt-cpp
RUN git clone https://github.com/Thalhammer/jwt-cpp.git /tmp/jwt-cpp \
    && cp -r /tmp/jwt-cpp/include/* /usr/include/ \
    && rm -rf /tmp/jwt-cpp

# Install minio
RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio \
    -O /usr/local/bin/minio && chmod +x /usr/local/bin/minio

RUN apt-get install -y zip \
    && git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg/ \
    && cd /opt/vcpkg/ \
    && ./bootstrap-vcpkg.sh \
    && chown -R ${UID}:${GID} /opt/vcpkg/