worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: false
cache-purge-enabled: true

server-port: 8080

pg-connection#env: POSTGRES_CONNECTION
s3-endpoint: "?"
s3-access-key#env: S3_ACCESS_KEY
s3-secret-key#env: S3_SECRET_KEY