config_vars: /app/configs/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        blob-repo:
            endpoint: $s3-endpoint
            bucket: pastes
            access_key: $s3-access-key
            secret_key: $s3-secret-key
            region: us-east-1  # doesn't matter for MinIO but is mandatory
            # s3-client: s3-client
        aws-sdk:
        metadata-repo:
        cache-purger: # purges nginx cache on paste DELETE
            load-enabled: $cache-purge-enabled # disabled in non-e2e tests
        write-service:
        jwt-verifier:
            public-key-path: /run/secrets/public.pem

        testsuite-support: {}

        congestion-control:
            only-rtc: false
            fake-mode: $is-testing

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-upload-create-url:
            path: /api/v2/paste/create-url
            method: POST
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        handler-upload-submit:
            path: /api/v2/paste/submit
            method: POST
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        handler-delete-paste:
            path: /api/v1/delete/{id}
            method: DELETE
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        postgres-db-1:
            dbconnection: $pg-connection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        # s3-client:
        #     endpoint: $s3-endpoint
        #     access-key: $s3-access-key
        #     secret-key: $s3-secret-key
        #     region: us-east-1  # doesn't matter for MinIO but is mandatory