server {
    set $read_backend "http://read-service:8080";
    set $write_backend "http://write-service:8080";
    set $user_backend "http://user-service:8080";

    listen 80;
    server_name pastebin.io;

    # api: auth
    location ~ ^/api/v2/auth/(refresh|signup|login)/?$ {
        limit_req zone=api_auth burst=10 nodelay;
        limit_req_status 429;

        proxy_pass $user_backend;

        if ($request_method !~ ^(POST)$) {
            return 405;
        }
    }

    # api: upload paste (strict rate limiting)
    location ~ ^/api/v2/paste/(create-url|submit)/?$ {
        limit_req zone=api_upload burst=10 nodelay;
        limit_req_status 429;

        proxy_pass $write_backend;

        if ($request_method !~ ^(POST)$) {
            return 405;
        }
    }

    # api: get or delete paste
    location ~ ^/api/v2/paste/delete/([a-zA-Z0-9_-]+)$ {
        limit_req zone=api_upload burst=20 nodelay;

        proxy_pass $write_backend;
        
        if ($request_method !~ ^(DELETE)$) {
            return 405;
        }
    }

    # api: get paste
    location ~ ^/api/v2/paste/([a-zA-Z0-9_-]+)$ {
        proxy_pass $read_backend;

        if ($request_method !~ ^(GET)$) {
            return 405;
        }
    }
}