worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 1
logger-level: debug

is-testing: false
cache-purge-enabled: true

server-port: 8080
grpc-friend-endpoint#env: GRPC_FRIEND_ENDPOINT

pg-connection#env: POSTGRES_CONNECTION
s3-public-endpoint#env: S3_PUBLIC_ENDPOINT
s3-access-key#env: S3_ACCESS_KEY
s3-secret-key#env: S3_SECRET_KEY