config_vars: /app/configs/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        fs-task-processor:
            worker_threads: $worker-fs-threads
        grpc-blocking-task-processor:  # For blocking gRPC channel creation
            worker_threads: $worker-grpc-threads
            thread_name: grpc-worker

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        blob-repo:
            public_endpoint: $s3-public-endpoint
            bucket: pastes
            access_key: $s3-access-key
            secret_key: $s3-secret-key
            region: us-east-1  # doesn't matter for MinIO but is mandatory
        metadata-repo:
        read-service:
        aws-sdk:
        jwt-verifier:
            public-key-path: /run/secrets/public.pem

        testsuite-support: {}

        congestion-control:
            only-rtc: false
            fake-mode: $is-testing

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-my-pastes:
            path: /api/v2/my-pastes
            method: GET
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        handler-get-paste-details:
            path: /api/v2/paste/{id}/details
            method: GET
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        handler-get-paste:
            path: /api/v2/paste/{id}
            method: GET
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB
            auth:
                type: bearer

        postgres-db-1:
            dbconnection: $pg-connection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        grpc-client-common:
            blocking-task-processor: grpc-blocking-task-processor
        grpc-client-factory:
            channel-args: {}
        # grpc-friends-client:
        #     endpoint: $grpc-friends-endpoint
        #     client-name: friends
        #     dedicated-channel-counts:
        #         AreFriends: 3
        #     factory-component: grpc-client-factory