name: Build and optionally test a service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      build-type:
        required: true
        type: string
        default: 'debug'
      run-tests:
        required: false
        type: boolean
        default: true
      run-in-docker:
        required: false
        type: boolean
        default: true
      upload-artifact:
        required: false
        type: string
        default: ""

env:
  VCPKG_COMMIT: ffc071e0c08432c60c9b64f00334c0227667931b
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg/cache
  VCPKG_INSTALLED_DIR: ${{ github.workspace }}/.vcpkg/installed
  VCPKG_MANIFEST_DIR: ${{ github.workspace }}/vcpkg

jobs:
  build-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache ccache directory
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-${{ github.ref }}-${{ github.run_number }}
          restore-keys: |
            ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-${{ github.ref }}-
            ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-

      - name: Cache vcpkg binary cache
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-binary-${{ runner.os }}-${{ inputs.service-name }}-${{ hashFiles('vcpkg/vcpkg.json') }}
          restore-keys: |
            vcpkg-binary-${{ runner.os }}-${{ inputs.service-name }}

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_INSTALLED_DIR }}
          key: vcpkg-installed-${{ runner.os }}-${{ inputs.service-name }}-${{ hashFiles('vcpkg/vcpkg.json') }}
          restore-keys: |
            vcpkg-binary-${{ runner.os }}-${{ inputs.service-name }}

      - name: Fix vcpkg permissions
        run: |
          mkdir -p $VCPKG_INSTALLED_DIR
          mkdir -p $VCPKG_DEFAULT_BINARY_CACHE

      - name: Build
        run: make ${{ inputs.run-in-docker && 'docker-' || '' }}build-${{ inputs.build-type }}
        working-directory: services/${{ inputs.service-name }}

      - name: Test
        if: inputs.run-tests && inputs.build-type == 'debug'
        run: make ${{ inputs.run-in-docker && 'docker-' || '' }}test-${{ inputs.build-type }} \
          DOCKER_EXTRA_OPTS="--security-opt seccomp=unconfined" \
          DOCKER_ENV="UBSAN_OPTIONS='print_stacktrace=1'"
          # --security-opt runs container in privileged mode
          # because otherwise StackUsageMonitor causes userver to SIGABRT in debug builds
        working-directory: services/${{ inputs.service-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifact != ''
        with:
          name: ${{ inputs.service-name }}-binary
          path: services/${{ inputs.service-name }}/build-${{ inputs.build-type }}/${{ inputs.upload-artifact }}